"""Utilities for describing AI video production workflows."""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Dict, List


@dataclass(frozen=True)
class Tool:
    """Represents a single AI assisted tool used in the workflow."""

    name: str
    category: str
    description: str
    url: str | None = None


@dataclass(frozen=True)
class WorkflowStep:
    """A step required for producing a video with AI tooling."""

    title: str
    order: int
    description: str
    recommended_tools: List[str] = field(default_factory=list)


TOOLS: List[Tool] = [
    Tool(
        name="Runway Gen-2",
        category="Text-to-Video",
        description="Generate short video clips directly from textual prompts or image references.",
        url="https://runwayml.com/",
    ),
    Tool(
        name="Pika Labs",
        category="Text-to-Video",
        description="Produce stylised motion clips from either text descriptions or still images.",
        url="https://pika.art/",
    ),
    Tool(
        name="Synthesia",
        category="Avatar Video",
        description="Create presenter-led clips with lip-synced avatars suitable for courses and marketing.",
        url="https://www.synthesia.io/",
    ),
    Tool(
        name="D-ID",
        category="Avatar Video",
        description="Animate portraits or uploaded images with realistic lip-syncing.",
        url="https://www.d-id.com/",
    ),
    Tool(
        name="HeyGen",
        category="Avatar Video",
        description="Produce personalised talking head videos with autogenerated subtitles.",
        url="https://www.heygen.com/",
    ),
    Tool(
        name="ElevenLabs",
        category="Voice Generation",
        description="Generate natural-sounding voice-overs from a script in multiple languages.",
        url="https://elevenlabs.io/",
    ),
    Tool(
        name="Descript Overdub",
        category="Voice Generation",
        description="Clone voices and edit narration using a text-based interface.",
        url="https://www.descript.com/overdub",
    ),
    Tool(
        name="Midjourney",
        category="Image Generation",
        description="Create base frames or concept art that can be animated later.",
        url="https://www.midjourney.com/",
    ),
    Tool(
        name="Stable Diffusion",
        category="Image Generation",
        description="Open-source model for generating high quality still images.",
        url="https://stability.ai/",
    ),
    Tool(
        name="EbSynth",
        category="Animation",
        description="Transfer the style of a keyframe to a sequence of video frames.",
        url="https://ebsynth.com/",
    ),
    Tool(
        name="Deforum",
        category="Animation",
        description="Animate Stable Diffusion renders with camera motion control.",
        url="https://github.com/deforum-art",
    ),
    Tool(
        name="Kaiber",
        category="Image Animation",
        description="Animate still images with dynamic camera movement for social clips.",
        url="https://www.kaiber.ai/",
    ),
    Tool(
        name="LeiaPix",
        category="Image Animation",
        description="Convert 2D images into depth-aware animations.",
        url="https://convert.leiapix.com/",
    ),
    Tool(
        name="Descript",
        category="Editing",
        description="Edit video using a transcript, remove filler words, and add captions automatically.",
        url="https://www.descript.com/",
    ),
    Tool(
        name="Adobe Premiere Pro",
        category="Editing",
        description="Professional timeline editor with AI-powered colour, framing, and audio tools.",
        url="https://www.adobe.com/products/premiere.html",
    ),
    Tool(
        name="CapCut",
        category="Editing",
        description="Template-driven editing with automatic subtitles, effects, and royalty-free music.",
        url="https://www.capcut.com/",
    ),
    Tool(
        name="Canva",
        category="Editing",
        description="Quick assembly of branded clips with stock footage and typography presets.",
        url="https://www.canva.com/",
    ),
]


WORKFLOW: List[WorkflowStep] = [
    WorkflowStep(
        title="نوشتن سناریو",
        order=1,
        description="ایده‌پردازی و آماده‌سازی متن اولیه برای روایت ویدیو.",
        recommended_tools=["ChatGPT", "Notion AI"],
    ),
    WorkflowStep(
        title="تولید تصاویر یا آواتار",
        order=2,
        description="ساخت تصاویر ثابت، آواتار یا فریم‌های مرجع برای مراحل بعدی.",
        recommended_tools=["Midjourney", "Stable Diffusion", "Synthesia", "D-ID"],
    ),
    WorkflowStep(
        title="تولید یا ضبط صدا",
        order=3,
        description="تولید گویندگی خودکار یا ضبط صدا و ویرایش آن برای هماهنگی با ویدیو.",
        recommended_tools=["ElevenLabs", "Descript Overdub", "Descript"],
    ),
    WorkflowStep(
        title="ساخت کلیپ‌های ویدیویی",
        order=4,
        description="تبدیل توضیحات متنی یا تصاویر به کلیپ‌های متحرک.",
        recommended_tools=["Runway Gen-2", "Pika Labs", "Kaiber", "LeiaPix"],
    ),
    WorkflowStep(
        title="ویرایش و ترکیب نهایی",
        order=5,
        description="ترکیب صدا، تصویر و متن در ویرایشگر و آماده‌سازی خروجی نهایی.",
        recommended_tools=["Descript", "Adobe Premiere Pro", "CapCut", "Canva"],
    ),
    WorkflowStep(
        title="انتشار و بهینه‌سازی",
        order=6,
        description="تنظیم فرمت خروجی، افزودن زیرنویس و انتشار در پلتفرم مقصد.",
        recommended_tools=["YouTube Studio", "CapCut"],
    ),
]


def _serialize_tools() -> List[Dict[str, str | None]]:
    return [asdict(tool) for tool in TOOLS]


def _serialize_workflow() -> List[Dict[str, str | int | List[str]]]:
    return [asdict(step) for step in sorted(WORKFLOW, key=lambda step: step.order)]


def get_ai_video_workflow() -> Dict[str, List[Dict[str, object]]]:
    """Return the curated AI video workflow and tool catalog."""

    return {"tools": _serialize_tools(), "workflow": _serialize_workflow()}
